id: P009568
initial_creation_type: ocr
source_metadata:
  id: bdr:W21618
  title: རྒྱ་བཟའ་བལ་བཟའི་རྣམ་ཐར།
  author: ''
  volumes:
    864ef5b6482749e6bdd59a2fbfafb23b:
      image_group_id: I1KG22773
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
